# Generated by Django 3.0.3 on 2020-04-10 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountInfos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acountInfos', to=settings.AUTH_USER_MODEL),
        ),
    ]
