# Generated by Django 3.0.3 on 2020-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountInfos', '0002_auto_20200410_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfo',
            name='islandOwnerID',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='createTime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='switchID',
            field=models.TextField(blank=True),
        ),
    ]
