# Generated by Django 3.0.3 on 2020-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountInfos', '0004_auto_20200410_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='createTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
