# Generated by Django 3.0.3 on 2020-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountInfos', '0005_auto_20200410_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='switchID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
