# Generated by Django 3.0.3 on 2020-04-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountInfos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandPassCode', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('hashTagDescription', models.TextField(blank=True)),
                ('reportCount', models.IntegerField(default=0)),
                ('createTime', models.DateField()),
                ('close', models.BooleanField(default=False)),
                ('accountInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postedIslands', to='accountInfos.AccountInfo')),
            ],
        ),
    ]
