# Generated by Django 3.0.3 on 2020-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islands', '0003_auto_20200410_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='close',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='createTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='hashTagDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='islandPassCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='reportCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
