# Generated by Django 3.0.3 on 2020-04-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islands', '0004_auto_20200410_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
